# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: yarn
    - run: yarn tsc
    - name: Create mongoDB Docker container for API testing
      uses: DigiPie/mongo-action@v1.0.1
    - run: yarn test
    - name: Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.2.0
      with:
        filename: coverage/cobertura-coverage.xml
        badge: true
        format: markdown
        output: both
